version: '2'

networks:
  personal:
    driver: bridge
    # external:
    #  name: srv_personal

services:
  bot:
    build: bot
    networks:
      - personal
    env_file:
      - bot/secrets.env
      - bot/local.env
  
  stats: 
    build: stats
    networks:
      - personal
    ports:
      - 3000:3000 # local dev
    volumes:
      - ./stats:/app
    env_file:
      - stats/secrets.env
