version: '2'

networks:
  personal:
    # driver: bridge
    external:
      name: srv_personal

services:
  bot:
    build: bot
    restart: on-failure
    networks:
      - personal
    env_file:
      - bot/secrets.env
  
  stats: 
    build: stats
    restart: on-failure
    networks:
      - personal
    ports:
      - 3000 #:3000 # local dev
    environment:
      - VIRTUAL_HOST=modlinker-stats.karel-kroeze.nl
      - VIRTUAL_PORT=3000
    env_file:
      - stats/secrets.env
